-- Migration: Add embedding columns to attributes table for AI similarity detection
-- Created: 2024-11-18

ALTER TABLE attributes
ADD COLUMN embedding TEXT,
ADD COLUMN embedding_updated_at TEXT;

-- Add comment for documentation
COMMENT ON COLUMN attributes.embedding IS 'JSON string of embedding vector generated by Gemini API for similarity detection';
COMMENT ON COLUMN attributes.embedding_updated_at IS 'Timestamp when embedding was last updated';
